openapi: 3.0.1
info:
  title: Library.Api
  version: '1.0'
paths:
  /authors:
    get:
      tags:
        - Library.Api
      operationId: get_authors
      parameters:
        - name: Accept
          in: header
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: {}
        '400':
          description: Bad Request
        '406':
          description: Not Acceptable
    post:
      tags:
        - Library.Api
      operationId: create_author
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorCreateDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
        '400':
          description: Bad Request
        '406':
          description: Not Acceptable
  /authors/{id}:
    get:
      tags:
        - Library.Api
      operationId: get_author
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: fields
          in: query
          style: form
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '406':
          description: Not Acceptable
    post:
      tags:
        - Library.Api
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
      responses:
        '404':
          description: Not Found
        '406':
          description: Not Acceptable
        '409':
          description: Conflict
    delete:
      tags:
        - Library.Api
      operationId: delete_author
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
        '406':
          description: Not Acceptable
  /authorcollections/{ids}:
    get:
      tags:
        - Library.Api
      operationId: get_author_collection
      parameters:
        - name: ids
          in: path
          required: true
          style: simple
          schema:
            $ref: '#/components/schemas/GuidListBinding'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AuthorDto'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '406':
          description: Not Acceptable
  /authorcollections:
    post:
      tags:
        - Library.Api
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AuthorCreateDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AuthorDto'
        '400':
          description: Bad Request
        '406':
          description: Not Acceptable
  /authors/{authorId}/books:
    get:
      tags:
        - Library.Api
      operationId: get_books_for_author
      parameters:
        - name: authorId
          in: path
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDtoLinkedCollectionResourceWrapperDto'
        '404':
          description: Not Found
        '406':
          description: Not Acceptable
    post:
      tags:
        - Library.Api
      operationId: create_book_for_author
      parameters:
        - name: authorId
          in: path
          required: true
          style: simple
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookCreateDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDto'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '406':
          description: Not Acceptable
  /authors/{authorId}/books/{bookId}:
    get:
      tags:
        - Library.Api
      operationId: get_book_for_author
      parameters:
        - name: authorId
          in: path
          required: true
          style: simple
          schema:
            type: string
        - name: bookId
          in: path
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDto'
        '404':
          description: Not Found
        '406':
          description: Not Acceptable
    delete:
      tags:
        - Library.Api
      operationId: delete_book_for_author
      parameters:
        - name: authorId
          in: path
          required: true
          style: simple
          schema:
            type: string
        - name: bookId
          in: path
          required: true
          style: simple
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
        '406':
          description: Not Acceptable
    put:
      tags:
        - Library.Api
      operationId: update_book_for_author
      parameters:
        - name: authorId
          in: path
          required: true
          style: simple
          schema:
            type: string
        - name: bookId
          in: path
          required: true
          style: simple
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookUpdateDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDto'
        '204':
          description: No Content
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '406':
          description: Not Acceptable
    patch:
      tags:
        - Library.Api
      operationId: partially_update_book_for_author
      parameters:
        - name: authorId
          in: path
          required: true
          style: simple
          schema:
            type: string
        - name: bookId
          in: path
          required: true
          style: simple
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDto'
        '204':
          description: No Content
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '406':
          description: Not Acceptable
  /:
    get:
      tags:
        - Library.Api
      operationId: get_root
      parameters:
        - name: Accept
          in: header
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LinkDto'
        '204':
          description: No Content
        '406':
          description: Not Acceptable
components:
  schemas:
    AuthorCreateDto:
      type: object
      properties:
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        dateOfBirth:
          type: string
          format: date-time
        genre:
          type: string
          nullable: true
        books:
          type: array
          items:
            $ref: '#/components/schemas/BookCreateDto'
          nullable: true
      additionalProperties: false
    AuthorDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          nullable: true
        age:
          type: integer
          format: int32
        genre:
          type: string
          nullable: true
      additionalProperties: false
    BookCreateDto:
      type: object
      properties:
        title:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
      additionalProperties: false
    BookDto:
      type: object
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/LinkDto'
          nullable: true
        id:
          type: string
          format: uuid
        title:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        authorId:
          type: string
          format: uuid
      additionalProperties: false
    BookDtoLinkedCollectionResourceWrapperDto:
      type: object
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/LinkDto'
          nullable: true
        value:
          type: array
          items:
            $ref: '#/components/schemas/BookDto'
          nullable: true
      additionalProperties: false
    BookUpdateDto:
      type: object
      properties:
        title:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
      additionalProperties: false
    GuidListBinding:
      type: object
      properties:
        guids:
          type: array
          items:
            type: string
            format: uuid
          nullable: true
      additionalProperties: false
    LinkDto:
      type: object
      properties:
        href:
          type: string
          nullable: true
        rel:
          type: string
          nullable: true
        method:
          type: string
          nullable: true
      additionalProperties: false
